#!/bin/sh

# Tests whether eslint can --fix one file to match another.

set -e
trap cleanup EXIT

cleanup() {
	rm -f "$FILE_INVALID_TEST"
}

FILE_INVALID="${1:-path/to/fileA.js}"
FILE_INVALID_TEST="${FILE_INVALID%.*}.test.${FILE_INVALID##*.}"
FILE_VALID="${2:-path/to/fileB.js}"

# Create backups of file A
cp "$FILE_INVALID" "$FILE_INVALID_TEST"

# Run eslint --fix on the backup of file A
npx eslint --fix "$FILE_INVALID_TEST"

# Compare the (fixed) copy of file A to the backup of file B
if ! diff -q "$FILE_INVALID_TEST" "$FILE_VALID" &>/dev/null; then
	echo "\033[1;31m✕\033[0m After eslint --fix, the files differ."
	diff "$FILE_INVALID_TEST" "$FILE_VALID" -y --color
	exit 1
fi

echo "\033[1;32m✔\033[0m $FILE_INVALID and $FILE_VALID are identical after eslint --fix."
