#!/bin/sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo ""
echo "📋 Testing examples..."
echo ""

for dir in vue ts js; do
	pushd "$SCRIPT_DIR/../examples/$dir" > /dev/null
	echo "\033[1mValidating examples/$dir/valid.$dir\033[0m"
	echo "\033[0;36meslint examples/$dir/valid.* --max-warnings 0\033[0m"
	npx eslint "**/valid.*" --max-warnings 0
	"$SCRIPT_DIR/compare" "invalid.$dir" "valid.$dir"
	echo ""
	popd > /dev/null
done

echo "✔ All tests passed!"
