#!/bin/sh

# This script runs the tests for all examples.

set -e

BASE_DIR="$(dirname "$0")/../examples"

echo

for dir in vue ts js; do
	echo "Testing \033[1mexamples/$dir\033[0m"
	pushd "$BASE_DIR/$dir" > /dev/null
	./test
	popd > /dev/null
	echo
done

echo "All tests passed! 🎉"
echo
